name: My Portfolio Page

on :
  push:
    branches: [feature/githubaction]

jobs:
  deploy-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /portfolio/
          webRenderer: canvaskit