name: My Portfolio CI/CD

on :
  push:
    branches: [feature/githubaction]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
    
      - name: Install dependencies
        run: |
         flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build Web
        run: flutter build web
