name: My Portfolio Webisite

on :
  push:
    branches:
      - [feature/github-actions]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
      
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.24.1'

        - name: Install Dependencies
          run: |
            flutter pub get

        - name: Analyze Code
          run: |
            flutter analyze

        - name: Build Web
          run: |
            flutter build web